// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeTracker.Infrastructure.Persistence;

#nullable disable

namespace TimeTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918121011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TimeTracker.Domain.Clients.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.TimeTracking.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Range");

                    b.Property<long?>("Range_End_Ticks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Range_End_Ticks");

                    b.Property<long>("Range_Start_Ticks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Range_Start_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Range_End_Ticks");

                    b.HasIndex("Range_Start_Ticks");

                    b.ToTable("TimeEntries", (string)null);
                });

            modelBuilder.Entity("TimeTracker.Domain.Projects.Project", b =>
                {
                    b.HasOne("TimeTracker.Domain.Clients.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TimeTracker.Domain.TimeTracking.TimeEntry", b =>
                {
                    b.HasOne("TimeTracker.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("TimeTracker.Domain.Tags.Tag", "Tags", b1 =>
                        {
                            b1.Property<Guid>("TimeEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.HasKey("TimeEntryId", "Name");

                            b1.ToTable("TimeEntryTags", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TimeEntryId");
                        });

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
