<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TimeTracker.Presentation</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
    <PackageReference Include="CommunityToolkit.Mvvm" />

    <!-- Инспектор Avalonia только в Debug -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeTracker.Application\TimeTracker.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\app.ico" />
  </ItemGroup>

</Project>
